const eventsData = [
    {
      title: "The Future of AI in Business and Society",
      description: "A deep dive into how artificial intelligence is reshaping industries, automating tasks, and influencing human decision-making.",
      organizer: "Tech Visionaries Summit",
      category: "AI AND THE FUTURE OF WORK",
      categoryColor: "bg-purple-200 text-purple-700",
      date: "2025-03-10",
      time: "09:00 AM - 03:00 PM",
      sponsored: "Yes",
      sponsor: "IT Solutions",
    },
    {
      title: "Innovations in Telemedicine: The Next Decade",
      description: "Explore the latest advancements in remote healthcare, AI-driven diagnostics, and patient monitoring solutions.",
      organizer: "Global Health Forum",
      category: "GLOBAL HEALTHCARE",
      categoryColor: "bg-blue-200 text-blue-700",
      date: "2025-04-22",
      time: "10:00 AM - 03:00 PM",
      sponsored: "Yes",
      sponsor: "MedTech Solutions",
    },
    {
      title: "E-Commerce Growth Strategies for 2025",
      description: "A masterclass on scaling online businesses, optimizing conversions, and leveraging AI for personalized customer experiences.",
      organizer: "Digital Commerce Association",
      category: "E-COMMERCE AND BUSINESS",
      categoryColor: "bg-green-200 text-green-700",
      date: "2025-03-09",
      time: "11:00 AM - 04:00 PM",
      sponsored: "No",
      sponsor: "-",
    },
    {
      title: "AI-Powered Marketing: Personalization at Scale",
      description: "Learn how AI-driven marketing tools can enhance audience segmentation, content recommendations, and advertising efficiency.",
      organizer: "Marketing Trends",
      category: "MARKETING & MEDIA",
      categoryColor: "bg-pink-200 text-pink-700",
      date: "2025-05-10",
      time: "08:00 AM - 10:00 PM",
      sponsored: "Yes",
      sponsor: "Google Ads",
    },
    {
      title: "Ethical AI in Business: Balancing Innovation and Responsibility",
      description: "Discussions on bias mitigation, data privacy, and responsible AI deployment in corporate environments.",
      organizer: "FutureTech Roundtable",
      category: "AI AND THE FUTURE OF WORK",
      categoryColor: "bg-purple-200 text-purple-700",
      date: "2025-05-05",
      time: "10:00 AM - 01:00 PM",
      sponsored: "No",
      sponsor: "-",
    },
    {
      title: "The Rise of Personalized Shopping Experiences",
      description: "Explore how AI and big data are driving hyper-personalization in e-commerce, enhancing customer retention.",
      organizer: "Retail Innovation Network",
      category: "E-COMMERCE AND BUSINESS",
      categoryColor: "bg-green-200 text-green-700",
      date: "2025-03-11",
      time: "09:00 AM - 01:00 PM",
      sponsored: "Yes",
      sponsor: "Shopify",
    },
    {
      title: "Cybersecurity in a Hyperconnected World",
      description: "Understand emerging threats, zero-trust architecture, and AI-powered cybersecurity defenses.",
      organizer: "Global Cybersecurity Conference",
      category: "TECH & SECURITY",
      categoryColor: "bg-red-200 text-red-700",
      date: "2025-06-15",
      time: "12:00 PM - 05:00 PM",
      sponsored: "Yes",
      sponsor: "CyberShield Inc.",
    },
    {
      title: "The Future of Remote Work & Virtual Collaboration",
      description: "Insights into hybrid work models, virtual reality meetings, and remote team productivity.",
      organizer: "WorkTech Summit",
      category: "FUTURE OF WORK",
      categoryColor: "bg-gray-200 text-gray-700",
      date: "2025-07-07",
      time: "10:00 AM - 03:00 PM",
      sponsored: "No",
      sponsor: "-",
    },
    {
      title: "Green Energy Innovations: The Next Frontier",
      description: "Explore advancements in solar, wind, and battery storage technologies shaping the future of energy.",
      organizer: "CleanTech Expo",
      category: "SUSTAINABILITY & ENERGY",
      categoryColor: "bg-green-300 text-green-800",
      date: "2025-08-18",
      time: "09:30 AM - 04:30 PM",
      sponsored: "Yes",
      sponsor: "EcoPower Solutions",
    },
    {
      title: "Space Exploration: Colonizing Mars and Beyond",
      description: "Join leading astrophysicists and engineers discussing the technology and strategy behind interplanetary travel.",
      organizer: "AstroTech Conference",
      category: "SPACE & TECHNOLOGY",
      categoryColor: "bg-indigo-200 text-indigo-700",
      date: "2025-09-12",
      time: "02:00 PM - 07:00 PM",
      sponsored: "Yes",
      sponsor: "SpaceX",
    },
  ];

  export default eventsData;